site_name: CyberDump 

theme:
  name: 'material'
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - navigation.footer
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
        
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  feature:
    - instant
    - tabs

nav:
  - Windows: 
    - Windows Shells: windows/page1.md
    - Windows Permissions: windows/page2.md
    - Reverse Shells: windows/page3.md
    - SeImpersonatePrivilege: windows/page4.md
  - Network Security:
    - TSL handshake: network_security/page1.md
    - SSL handshake: network_security/page2.md

extra_css:
  - stylesheets/extra.css