site_name: CyberDump 

theme:
  name: 'material'
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.footer
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
        
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  feature:
    - instant
    - tabs

nav:
  - Windows: 
    - Windows Shells: windows/page1.md
    - Windows Permissions: windows/page2.md
    - Reverse Shells: windows/page3.md
    - SeImpersonatePrivilege: windows/page4.md
    - On Cross Compilation: windows/page5.md
    - Windows Services: windows/page6.md
    - Weak Service Permissions: windows/page7.md
    - Unquoted Service Path: windows/page8.md
    - DLL Hijacking: windows/page9.md
    - UAC Bypass: windows/page10.md
    - Always Install Elevated: windows/page11.md
    - Files with Sensitive Data: windows/page12.md
    - Windows Hashes: windows/page13.md
    - Windows Vault: windows/page14.md
    - Scheduled Tasks: windows/page15.md
    - Critical Registry Paths: windows/page16.md
    - Useful Tools: windows/page17.md
    - AMSI Bypass: windows/page18.md
  - Linux:
    - Linux Shell: linux/page1.md
    - File System Permissions: linux/page2.md
    - PATH Hijacking: linux/page3.md
    - SUID Exploitation: linux/page4.md
    - SUDO Exploitation: linux/page5.md
    - Wildcard Exploitation: linux/page6.md
    - Unshadow Attack: linux/page7.md
    - System Enumeration: linux/page8.md
    - Cronjob Enumeration: linux/page9.md
    - Capabilities Enumeration: linux/page10.md
    - Local Service Exploitation: linux/page11.md
    - Binary Exploitation: linux/page12.md
    - Kernel Exploitation: linux/page13.md

extra_css:
  - stylesheets/extra.css